---
- name: Install prerequisite packages
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Create system user
  become: true
  ansible.builtin.user:
    name: "{{ bamboo_system_user }}"
    system: true
    state: present
    create_home: false

- name: Create installation directory
  become: true
  ansible.builtin.file:
    path: "{{ bamboo_installation_directory }}"
    state: directory
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"

- name: Create database users
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ _db.username }}"
    password: "{{ _db.password }}"
    conn_limit: "-1"
  loop: "{{ bamboo_database | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: _db
  when: _db.enabled | bool
  no_log: false

- name: Create databases
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ _db.name }}"
    owner: "{{ _db.username }}"
    encoding: UTF-8
    lc_collate: "{{ bamboo_locale }}"
    lc_ctype: "{{ bamboo_locale }}"
    template: template0
  loop: "{{ bamboo_database | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: _db
  when: _db.enabled | bool
  no_log: false

- name: Grant privs on db
  become: true
  become_user: postgres
  community.postgresql.postgresql_privs:
    database: "{{ _db.name }}"
    role: "{{ _db.username }}"
    state: present
    privs: ALL
    type: database
  loop: "{{ bamboo_database | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: _db
  when: _db.enabled | bool
  no_log: false

- name: Unpack Bamboo to installation direcotory
  become: true
  ansible.builtin.unarchive:
    src: "{{ bamboo_base_url }}/atlassian-bamboo-{{ bamboo_version.major }}.{{ bamboo_version.minor }}.{{ bamboo_version.patch }}-standalone.tar.gz"
    dest: "{{ bamboo_installation_directory }}"
    creates: "{{ bamboo_installation_directory }}/bamboo.sh"
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Copy Bamboo config to dest
  become: true
  become_user: "{{ bamboo_system_user }}"
  ansible.builtin.template:
    src: "wrapper.conf.j2"
    dest: "{{ bamboo_installation_directory }}/conf/wrapper.conf"
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"
  notify: restart bamboo

# TODO: Due to the Bamboo daemon actively writing to this file, we only want to create it if it doesn't exist.
#       Not sure if this is the best approach but it will do for now.
- name: Create bamboo.cfg.xml if required
  block:
    - name: Check if bamboo.cfg.xml already exists
      ansible.builtin.stat:
        path: "{{ bamboo_installation_directory }}/bamboo.cfg.xml"
      register: _bamboo_cfg

    - name: Copy Bamboo bamboo.cfg.xml to dest
      become: true
      become_user: "{{ bamboo_system_user }}"
      ansible.builtin.template:
        src: "bamboo.cfg.xml.j2"
        dest: "{{ bamboo_installation_directory }}/bamboo.cfg.xml"
        owner: "{{ bamboo_system_user }}"
        group: "{{ bamboo_system_user }}"
      when: not _bamboo_cfg.stat.exists
      notify: restart bamboo

# TODO: This is only partially working. Currently, I'm only updating the license key. This may change in the future.
- name: Update bamboo.cfg.xml if required
  become: true
  become_user: "{{ bamboo_system_user }}"
  community.general.xml:
    path: "{{ bamboo_installation_directory }}/bamboo.cfg.xml"
    xpath: /application-configuration/properties/property[@name="license.string"]
    value: "{{ bamboo_license_string }}"
  notify: restart bamboo

# TODO: I thought that Bamboo came with postgresql preinstalled? Not sure if this is a build error or something that's now
#       required when installing Bamboo Datacenter. This may need updating if this is a bug.
- name: Install Postgresql JDBC driver
  become: true
  become_user: "{{ bamboo_system_user }}"
  ansible.builtin.get_url:
    url: "{{ postgresql_java_base_url }}/postgresql-{{ postgresql_java_version.major }}.{{ postgresql_java_version.minor }}.{{ postgresql_java_version.patch }}.jar"
    dest: "{{ bamboo_installation_directory }}/webapp/WEB-INF/lib/postgresql-{{ postgresql_java_version.major }}.{{ postgresql_java_version.minor }}.{{ postgresql_java_version.patch }}.jar"
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"

- name: Create JDK dest directory
  become: true
  ansible.builtin.file:
    path: "{{ bamboo_installation_directory }}/jdk"
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"
    mode: 0770
    state: directory

- name: Unpack JDK to installation directory
  become: true
  ansible.builtin.unarchive:
    src: "{{ temurin_base_url }}/temurin{{ temurin_version.major }}-binaries/releases/download/jdk-{{ temurin_version.major }}.{{ temurin_version.minor }}.{{ temurin_version.patch }}%2B{{ temurin_version.build }}/OpenJDK11U-jdk_x64_linux_hotspot_{{ temurin_version.major }}.{{ temurin_version.minor }}.{{ temurin_version.patch }}_{{ temurin_version.build }}.tar.gz"
    dest: "{{ bamboo_installation_directory }}/jdk"
    creates: "{{ bamboo_installation_directory }}/jdk/release"
    remote_src: true
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"
    extra_opts:
      - "--strip-components=1"

- name: Create Bamboo required directories
  become: true
  ansible.builtin.file:
    path: "{{ bamboo_installation_directory }}/{{ item }}"
    owner: "{{ bamboo_system_user }}"
    group: "{{ bamboo_system_user }}"
    mode: 0770
    state: directory
  loop:
    - artifacts
    - xml-data/configuration
    - xml-data/builds
    - xml-data/build-dir
    - backups
    - index
    - temp

- name: Create the Bamboo systemd service
  become: true
  ansible.builtin.template:
    src: "bamboo.service.j2"
    dest: "/lib/systemd/system/bamboo.service"
    owner: root
    group: root
    mode: 444
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t

- name: Enable the Bamboo systemd service
  become: true
  ansible.builtin.systemd:
    name: bamboo
    state: started
    daemon_reload: true
    enabled: true
